"""Initial migration

Revision ID: 51ec1ba63d94
Revises: 
Create Date: 2026-04-11 22:09:07.658920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ec1ba63d94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_dependent_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_health_event_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_household_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_health_events_dependent_id'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_household_id'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_id'), table_name='health_events')
    op.drop_table('health_events')
    op.drop_index(op.f('ix_dependents_household_id'), table_name='dependents')
    op.drop_index(op.f('ix_dependents_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_table('households')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('primary_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('village_town', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('households_pkey'))
    )
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('dependents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('household_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('child', 'adult', 'elder', 'pregnant', name='dependenttype'), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sex', postgresql.ENUM('male', 'female', 'other', name='sex'), autoincrement=False, nullable=False),
    sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('dependents_household_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dependents_pkey'))
    )
    op.create_index(op.f('ix_dependents_id'), 'dependents', ['id'], unique=False)
    op.create_index(op.f('ix_dependents_household_id'), 'dependents', ['household_id'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dependent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('household_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('schedule_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('vaccination', 'checkup', 'vitamin', 'reminder', name='eventcategory'), autoincrement=False, nullable=False),
    sa.Column('dose_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('window_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('window_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('upcoming', 'due', 'overdue', 'completed', name='eventstatus'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('schedule_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['dependents.id'], name=op.f('health_events_dependent_id_fkey')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('health_events_household_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('health_events_pkey'))
    )
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)
    op.create_index(op.f('ix_health_events_household_id'), 'health_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_health_events_dependent_id'), 'health_events', ['dependent_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('health_event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dependent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('household_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'snoozed', 'acknowledged', 'completed', name='reminderstatus'), autoincrement=False, nullable=False),
    sa.Column('snoozed_until', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['dependents.id'], name=op.f('reminders_dependent_id_fkey')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('reminders_health_event_id_fkey')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('reminders_household_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reminders_pkey'))
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_household_id'), 'reminders', ['household_id'], unique=False)
    op.create_index(op.f('ix_reminders_health_event_id'), 'reminders', ['health_event_id'], unique=False)
    op.create_index(op.f('ix_reminders_dependent_id'), 'reminders', ['dependent_id'], unique=False)
    # ### end Alembic commands ###
