"""Initial stabilization

Revision ID: 8e3d27626eea
Revises: 
Create Date: 2026-04-12 19:17:42.021188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d27626eea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('auth_id', sa.String(), nullable=True),
        sa.Column('primary_language', sa.String(length=10), nullable=False),
        sa.Column('village_town', sa.String(length=200), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('district', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_auth_id'), 'households', ['auth_id'], unique=False)
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_index(op.f('ix_households_username'), 'households', ['username'], unique=True)

    op.create_table('dependents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('household_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('type', sa.Enum('child', 'adult', 'elder', 'pregnant', name='dependenttype'), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=False),
        sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex'), nullable=False),
        sa.Column('expected_delivery_date', sa.Date(), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_household_id'), 'dependents', ['household_id'], unique=False)
    op.create_index(op.f('ix_dependents_id'), 'dependents', ['id'], unique=False)

    op.create_table('health_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('dependent_id', sa.String(), nullable=False),
        sa.Column('household_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=300), nullable=False),
        sa.Column('schedule_key', sa.String(length=100), nullable=False),
        sa.Column('category', sa.Enum('vaccination', 'checkup', 'vitamin', 'reminder', name='eventcategory'), nullable=False),
        sa.Column('dose_number', sa.Integer(), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('window_start', sa.Date(), nullable=True),
        sa.Column('window_end', sa.Date(), nullable=True),
        sa.Column('status', sa.Enum('upcoming', 'due', 'overdue', 'completed', name='eventstatus'), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('completed_by', sa.String(length=200), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('schedule_version', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dependent_id'], ['dependents.id'], ),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_dependent_id'), 'health_events', ['dependent_id'], unique=False)
    op.create_index(op.f('ix_health_events_household_id'), 'health_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)

    op.create_table('reminders',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('health_event_id', sa.String(), nullable=False),
        sa.Column('dependent_id', sa.String(), nullable=False),
        sa.Column('household_id', sa.String(), nullable=False),
        sa.Column('event_name', sa.String(length=300), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'snoozed', 'acknowledged', 'completed', name='reminderstatus'), nullable=False),
        sa.Column('snoozed_until', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dependent_id'], ['dependents.id'], ),
        sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], ),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_dependent_id'), 'reminders', ['dependent_id'], unique=False)
    op.create_index(op.f('ix_reminders_health_event_id'), 'reminders', ['health_event_id'], unique=False)
    op.create_index(op.f('ix_reminders_household_id'), 'reminders', ['household_id'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)

    op.create_table('conversations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('household_id', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_household_id'), 'conversations', ['household_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)

    op.create_table('health_notes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('household_id', sa.String(), nullable=False),
        sa.Column('note', sa.String(length=1000), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_notes_household_id'), 'health_notes', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_notes')
    op.drop_table('conversations')
    op.drop_table('reminders')
    op.drop_table('health_events')
    op.drop_table('dependents')
    op.drop_table('households')
    # ### end Alembic commands ###
